### ISSUE TITLE
Add codemod to extract methods from instance that are not instance specific

### ISSUE THREAD

**Issue by SergioCrisostomo** [SergioCrisostomo/vue-codemods#1]
If a method does not use `this` we should extract it from the instance and have it as a global function assignment `const functionName = () => {... etc`

**Comment by SergioCrisostomo** [comment]
Fixed in 051f97c36fabd6f5381ba7fecefcd439f0197ffb

**Comment by webistomin** [comment]
Can you explain the benefits of this approach?

**Comment by SergioCrisostomo** [comment]
Hi @webistomin! 
There are different reasons for wanting to remove methods from a Vue component that are not dependent on the instance. I do not mean we should always do it, but by doing it we can: 
 - prevent creating "fat" instances with methods that could be outside the instance and do not need to be in memory of every object/instance
 -  identify possible utils functions and extract them to another file to keep the file size manageable
 - better test functions not related to the instance

If a method does not use the `this` then it can live outside the component. In some cases it makes sense to keep it so all the logic is in one place. This codemod allows to identify these and extract them.

**Comment by webistomin** [comment]
> Hi @webistomin!
> There are different reasons for wanting to remove methods from a Vue component that are not dependent on the instance. I do not mean we should always do it, but by doing it we can:
> 
> * prevent creating "fat" instances with methods that could be outside the instance and do not need to be in memory of every object/instance
> * identify possible utils functions and extract them to another file to keep the file size manageable
> * better test functions not related to the instance
> 
> If a method does not use the `this` then it can live outside the component. In some cases it makes sense to keep it so all the logic is in one place. This codemod allows to identify these and extract them.

Thanks!
